# Random Sampling

In [1]:
import numpy as np
from numpy import random

In [2]:
np.__version__

'1.17.3'

## Simple random data

Q1. Create an array of shape (3, 2) and populate it with random samples from a uniform distribution over [0, 1).

In [5]:
random.random((3,2))

array([[0.8626807 , 0.68320643],
       [0.3314575 , 0.12912764],
       [0.03309256, 0.55981272]])

Q2. Create an array of shape (1000, 1000) and populate it with random samples from a standard normal distribution. And verify that the mean and standard deviation is close enough to 0 and 1 repectively.

In [7]:
x = random.normal(0,1,(1000,1000))
print(np.mean(x))
print(np.std(x))

0.0009199120006995335
1.0004395248551465


Q3. Create an array of shape (3, 2) and populate it with random integers ranging from 0 to 3 (inclusive) from a discrete uniform distribution.

In [9]:
#random.randint(0,3,size=(3,2))#3 exclusive
random.random_integers(0,3,size=(3,2))

array([[1, 0],
       [3, 0],
       [1, 2]])

Q4. Extract 1 elements from x randomly such that each of them would be associated with probabilities .3, .5, .2. Then print the result 10 times.

In [11]:
x = ['3 out of 10', '5 out of 10', '2 out of 10']
for i in range(10):
    print(random.choice(x,p=[.3,.5,.2]))

5 out of 10
5 out of 10
5 out of 10
2 out of 10
2 out of 10
5 out of 10
5 out of 10
5 out of 10
2 out of 10
3 out of 10


Q5. Extract 3 different integers from 0 to 9 randomly with the same probabilities.

In [12]:
random.choice(10,size=3)

array([6, 5, 7])

## Permutations

Q6. Shuffle numbers between 0 and 9 (inclusive).

In [14]:
x = np.arange(10)
random.shuffle(x)

In [15]:
# Or
random.permutation(x)

array([6, 4, 9, 3, 5, 8, 7, 0, 2, 1])

## Random generator

Q7. Assign number 10 to the seed of the random generator so that you can get the same value next time.

In [16]:
random.seed(10)