# Sorting, searching, and counting

In [1]:
import numpy as np

In [2]:
np.__version__

'1.17.3'

## Sorting

Q1. Sort x along the second axis.

In [3]:
x = np.array([[1,4],[3,1]])
np.sort(x,axis = 1)

array([[1, 4],
       [1, 3]])

Q2. Sort pairs of surnames and first names and return their indices. (first by surname, then by name).

In [4]:
surnames =    ('Hertz',    'Galilei', 'Hertz')
first_names = ('Heinrich', 'Galileo', 'Gustav')
np.lexsort((first_names, surnames))

array([1, 2, 0], dtype=int64)

Q3. Get the indices that would sort x along the second axis.

In [9]:
x = np.array([[1,4],[3,1]])
np.argsort(x,axis=1)

array([[0, 1],
       [1, 0]], dtype=int64)

Q4. Create an array such that its fifth element would be the same as the element of sorted x, and it divide other elements by their value.

In [12]:
x = np.random.permutation(10)
print ("x =", x)
np.partition(x,5)

x = [0 2 4 6 1 9 8 7 3 5]


array([0, 1, 3, 4, 2, 5, 8, 7, 6, 9])

Q5. Create the indices of an array such that its third element would be the same as the element of sorted x, and it divide other elements by their value.

In [14]:
x = np.random.permutation(10)
print ("x =", x)
part = np.partition(x,3)
indice = np.argpartition(x,3)
print ('partitioned =',part)
print ('indices =',indice)


x = [2 9 5 1 4 3 8 6 7 0]
partitioned = [1 0 2 3 4 5 9 6 7 8]
indices = [3 9 0 5 4 2 1 7 8 6]


## Searching

Q6. Get the maximum and minimum values and their indices of x along the second axis.

In [16]:
x = np.random.permutation(10).reshape(2, 5)
print ("x =", x)
print('maximum values =', np.max(x,axis=1))
print('max indices =', np.argmax(x,axis=1))
print('minimum values =', np.min(x,axis=1))
print('min indices =', np.argmin(x,axis=1))

x = [[8 0 5 9 4]
 [2 7 3 1 6]]
maximum values = [9 7]
max indices = [3 1]
minimum values = [0 1]
min indices = [1 3]


Q7. Get the maximum and minimum values and their indices of x along the second axis, ignoring NaNs.

In [17]:
x = np.array([[np.nan, 4], [3, 2]])
print('maximum values ignoring NaNs =', np.nanmax(x,axis=1))
print('max indices =', np.nanargmax(x,axis=1))
print('minimum values ignoring NaNs =', np.nanmin(x,axis=1))
print('min indices =', np.nanargmin(x,axis=1))

maximum values ignoring NaNs = [4. 3.]
max indices = [1 0]
minimum values ignoring NaNs = [4. 2.]
min indices = [1 1]


Q8. Get the values and indices of the elements that are bigger than 2 in x.


In [24]:
x = np.array([[1, 2, 3], [1, 3, 5]])
print('Values bigger than 2:', x[x>2])
print('indices of values bigger than 2:',np.where(x > 2))

Values bigger than 2: [3 3 5]
indices of values bigger than 2: (array([0, 1, 1], dtype=int64), array([2, 1, 2], dtype=int64))


Q9. Get the indices of the elements that are bigger than 2 in the flattend x.

In [28]:
x = np.array([[1, 2, 3], [1, 3, 5]])
np.flatnonzero(x>2)

array([2, 4, 5], dtype=int64)

Q10. Check the elements of x and return 0 if it is less than 0, otherwise the element itself.

In [30]:
x = np.arange(-5, 4).reshape(3, 3)
np.where(x>0,x,0)

array([[0, 0, 0],
       [0, 0, 0],
       [1, 2, 3]])

Q11. Get the indices where elements of y should be inserted to x to maintain order.

In [31]:
x = [1, 3, 5, 7, 9]
y = [0, 4, 2, 6]
np.searchsorted(x,y)

array([0, 2, 1, 3], dtype=int64)

## Counting

Q12. Get the number of nonzero elements in x.

In [32]:
x = [[0,1,7,0,0],[3,0,0,2,19]]
np.count_nonzero(x)

5