# Linear algebra

In [1]:
import numpy as np

In [2]:
np.__version__

'1.17.3'

## Matrix and vector products

Q1. Predict the results of the following code.

In [3]:
x = [1,2]
y = [[4, 1], [2, 2]]
print(np.dot(x, y) == np.array([8,5]))
print(np.dot(y, x) == np.array([6,6]))
print(np.matmul(x, y) == np.array([8,5]))
print(np.inner(x, y) == np.array([6,6]))
print(np.inner(y, x) == np.array([6,6]))

[ True  True]
[ True  True]
[ True  True]
[ True  True]
[ True  True]


Q2. Predict the results of the following code.

In [4]:
x = [[1, 0], [0, 1]]
y = [[4, 1], [2, 2], [1, 1]]
print(np.dot(y, x) == np.array([[4, 1], [2, 2], [1, 1]]))
print(np.matmul(y, x) ==np.array([[4, 1], [2, 2], [1, 1]]))


[[ True  True]
 [ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]
 [ True  True]]


Q3. Predict the results of the following code.

In [5]:
x = np.array([[1, 4], [5, 6]])
y = np.array([[4, 1], [2, 2]])
print(np.vdot(x, y) == 1*4+4*1+5*2+6*2)
print(np.vdot(y, x) == 30)
print(np.dot(x.flatten(), y.flatten()) == 30)
print (np.inner(x.flatten(), y.flatten())==30)
print ((x*y).sum()==30)

True
True
True
True
True


Q4. Predict the results of the following code.

In [6]:
x = np.array(['a', 'b'], dtype=object)
y = np.array([1, 2])
print (np.inner(x, y) == 'abb')
print (np.inner(y, x) == 'abb')
print (np.outer(x, y))
print (np.outer(y, x))

True
True
[['a' 'aa']
 ['b' 'bb']]
[['a' 'b']
 ['aa' 'bb']]


## Decompositions

Q5. Get the lower-trianglular `L` in the Cholesky decomposition of x and verify it.

In [7]:
x = np.array([[4, 12, -16], [12, 37, -43], [-16, -43, 98]], dtype=np.int32)
#decomp:
L = np.linalg.cholesky(x)
print(L)
#verify:
np.dot(L,L.T)

[[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8.  5.  3.]]


array([[  4.,  12., -16.],
       [ 12.,  37., -43.],
       [-16., -43.,  98.]])

Q6. Compute the qr factorization of x and verify it.

In [8]:
x = np.array([[12, -51, 4], [6, 167, -68], [-4, 24, -41]], dtype=np.float32)
#decomp:
q,r = np.linalg.qr(x)
print('q=\n',q)
print('r=\n',r)
#verify:
print(np.dot(q,r))

q=
 [[-0.85714287  0.3942857   0.33142856]
 [-0.42857143 -0.9028571  -0.03428571]
 [ 0.2857143  -0.17142858  0.94285715]]
r=
 [[ -14.  -21.   14.]
 [   0. -175.   70.]
 [   0.    0.  -35.]]
[[ 12. -51.   4.]
 [  6. 167. -68.]
 [ -4.  24. -41.]]


Q7. Factor x by Singular Value Decomposition and verify it.

In [9]:
x = np.array([[1, 0, 0, 0, 2], [0, 0, 3, 0, 0], [0, 0, 0, 0, 0], [0, 2, 0, 0, 0]], dtype=np.float32)
#decomp:
u,sigma,v = np.linalg.svd(x,full_matrices=False)
print('u=\n',u)
print('sigma=\n',sigma)
print('v=\n',v)
#verify
print(np.dot(np.dot(u,np.diag(sigma)),v))


u=
 [[ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0. -1.]
 [ 0.  0.  1.  0.]]
sigma=
 [3.       2.236068 2.       0.      ]
v=
 [[-0.         0.         1.        -0.         0.       ]
 [ 0.4472136  0.         0.         0.         0.8944272]
 [-0.         1.         0.        -0.         0.       ]
 [ 0.         0.         0.         1.         0.       ]]
[[1. 0. 0. 0. 2.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]]


## Matrix eigenvalues

Q8. Compute the eigenvalues and right eigenvectors of x. (Name them eigenvals and eigenvecs, respectively)

In [10]:
x = np.diag((1, 2, 3))
eigenvals,eigenvecs = np.linalg.eig(x)
print('eigenvals:\n',eigenvals)
print('eigenvecs:\n',eigenvecs)

eigenvals:
 [1. 2. 3.]
eigenvecs:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Q9. Predict the results of the following code.

In [11]:
np.array_equal(np.dot(x, eigenvecs), eigenvals * eigenvecs)
#this should be equal.

True

## Norms and other numbers

Q10. Calculate the Frobenius norm and the condition number of x.

In [12]:
x = np.arange(1, 10).reshape((3, 3))
print('norm:',np.linalg.norm(x))
print('p=2 condition:',np.linalg.cond(x,p=2))
print('p=-2 condition:',np.linalg.cond(x,p=-2))

norm: 16.881943016134134
p=2 condition: 3.813147060626918e+16
p=-2 condition: 2.6225057258494257e-17


Q11. Calculate the determinant of x.

In [13]:
x = np.arange(1, 5).reshape((2, 2))
np.linalg.det(x)

-2.0000000000000004

Q12. Calculate the rank of x.

In [14]:
x = np.eye(4)
np.linalg.matrix_rank(x)

4

Q13. Compute the sign and natural logarithm of the determinant of x.

In [15]:
x = np.arange(1, 5).reshape((2, 2))
np.linalg.slogdet(x)#suitable for high dimension analysis

(-1.0, 0.6931471805599455)

Q14. Return the sum along the diagonal of x.

In [16]:
x = np.eye(4)
np.trace(x)

4.0

## Solving equations and inverting matrices

Q15. Compute the inverse of x.

In [17]:
x = np.array([[1., 2.], [3., 4.]])
print(np.linalg.solve(x,np.eye(2)))
np.linalg.inv(x)

[[-2.   1. ]
 [ 1.5 -0.5]]


array([[-2. ,  1. ],
       [ 1.5, -0.5]])